name: my
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=4.10.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bleach=6.3.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - catboost=1.2.7
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - executing=2.2.1
  - expat=2.7.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.16
  - getopt-win32=0.1
  - graphite2=1.3.14
  - graphviz=13.1.2
  - gts=0.7.6
  - h11=0.16.0
  - harfbuzz=11.4.5
  - html5lib=1.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - icc_rt=2022.1.0
  - icu=75.1
  - idna=3.11
  - intel-openmp=2023.1.0
  - ipykernel=6.31.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - json5=0.12.1
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.9
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgd=2.3.3
  - libglib=2.84.4
  - libhwloc=2.12.1
  - libiconv=1.16
  - libpng=1.6.50
  - libsodium=1.0.20
  - libtiff=4.5.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.2.1
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - narwhals=2.15.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8
  - pandocfilters=1.5.1
  - pango=1.56.4
  - parso=0.8.5
  - pcre2=10.46
  - phik=0.12.5
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.5.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-graphviz=0.21
  - python-json-logger=4.0.0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.28.0
  - scikit-learn=1.7.1
  - scipy=1.15.3
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.6.1
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - dacite==1.9.2
      - filetype==1.2.0
      - fonttools==4.61.1
      - llvmlite==0.45.1
      - matplotlib==3.10.7
      - minify-html==0.18.1
      - multimethod==1.12
      - numba==0.62.1
      - pillow==12.1.0
      - puremagic==1.30
      - pydantic==2.12.5
      - pyparsing==3.3.1
prefix: C:\Users\velor\anaconda3\envs\my
